[project]
name = "pcre-to-cpp"
version = "0.1.0"
description = "PCRE to CPP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.6.0",
    "pyyaml>=6.0.3",
    "ruff>=0.14.9",
    "tokenizers>=0.22.1",
]
